const VACANCYCARD = [
    {
        id: '1',
        promoImg: 'img/Prof-Photo.png',
        status: 'Новая',
        response: false,
        youResponded: false,
        name: 'Продавец-консультант (ТРЦ Дарынок, ТРЦ Рив Гош, ТРЦ Нью Вей, м. Дарница)',
        logo: 'img/Logo.png',
        salary: '10 000 — 15 000 ₴',
        comment: 'Ставка + процент от продаж',
        сompanyName: 'FISHKI.UA',
        city: 'Киев',
        benefits: [
            'Обеды в офис','Гибкий график','Компенсация спортзала'
        ],
        publicationTime: 'publicationTime',
        response: 'response',
        addToFavorites: 'addToFavorites',
        disLike: false,
    },
    {
        id: '2',
        promoImg: 'img/Prof-Photo.png',
        status: 'Новая',
        response: false,
        youResponded: false,
        name: 'Менеджер по продажам',
        logo: 'img/Logo.png',
        salary: '18 000 — 30 000 ₴',
        comment: '',
        сompanyName: 'FISHKI.UA',
        city: 'Киев',
        benefits: [
            'Гибкий график'
        ],
        publicationTime: 'publicationTime',
        response: 'response',
        addToFavorites: 'addToFavorites',
        disLike: false,
    },
    {
        id: '3',
        promoImg: 'img/Prof-Photo.png',
        status: 'Новая',
        response: false,
        youResponded: false,
        name: 'Грузчик на склад',
        logo: 'img/Logo.png',
        salary: '10 000 — 12 000 ₴',
        comment: '',
        сompanyName: 'FISHKI.UA',
        city: 'Киев',
        benefits: [
            
        ],
        publicationTime: 'publicationTime',
        response: 'response',
        addToFavorites: 'addToFavorites',
        disLike: false,
    },
    {
        id: '4',
        promoImg: 'img/Prof-Photo.png',
        status: 'Новая',
        response: false,
        youResponded: false,
        name: 'Парикмахер',
        logo: 'img/Logo.png',
        salary: '10 000 — 20 000 ₴',
        comment: 'Ставка + процент от продаж',
        сompanyName: 'FISHKI.UA',
        city: 'Киев',
        benefits: [
            
        ],
        publicationTime: 'publicationTime',
        response: 'response',
        addToFavorites: 'addToFavorites',
        disLike: false,
    },
    {
        id: '5',
        promoImg: 'img/Prof-Photo.png',
        status: 'Новая',
        response: false,
        youResponded: false,
        name: 'Юрист',
        logo: 'img/Logo.png',
        salary: '20 000 — 45 000 ₴',
        comment: '',
        сompanyName: 'FISHKI.UA',
        city: 'Киев',
        benefits: [
            
        ],
        publicationTime: 'publicationTime',
        response: 'response',
        addToFavorites: 'addToFavorites',
        disLike: false,
    },
    {
        id: '6',
        promoImg: 'img/Prof-Photo.png',
        status: 'Новая',
        response: false,
        youResponded: false,
        name: 'Продавец-консультант',
        logo: 'img/Logo.png',
        salary: '10 000 — 15 000 ₴',
        comment: 'Ставка + процент от продаж',
        сompanyName: 'FISHKI.UA',
        city: 'Киев',
        benefits: [
            'Гибкий график','Скидки сотрудникам'
        ],
        publicationTime: 'publicationTime',
        response: 'response',
        addToFavorites: 'addToFavorites',
        disLike: false,
    },
    {
        id: '7',
        promoImg: 'img/Prof-Photo.png',
        status: 'Новая',
        response: false,
        youResponded: false,
        name: 'Продавец-консультант',
        logo: 'img/Logo.png',
        salary: '10 000 — 15 000 ₴',
        comment: 'Ставка + процент от продаж',
        сompanyName: 'FISHKI.UA',
        city: 'Киев',
        benefits: [
            'Обеды в офис','Гибкий график','Компенсация спортзала'
        ],
        publicationTime: 'publicationTime',
        response: 'response',
        addToFavorites: 'addToFavorites',
        disLike: false,
    },
    {
        id: '8',
        promoImg: 'img/Prof-Photo.png',
        status: 'Новая',
        response: false,
        youResponded: false,
        name: 'Врач-эндокринолог',
        logo: 'img/Logo.png',
        salary: '15 000 — 30 000 ₴',
        comment: '',
        сompanyName: '2 городская поликлиника',
        city: 'Киев',
        benefits: [
            'Обеды в офис','Гибкий график','Компенсация спортзала'
        ],
        publicationTime: 'publicationTime',
        response: 'response',
        addToFavorites: 'addToFavorites',
        disLike: false,
    },
    {
        id: '9',
        promoImg: 'img/Prof-Photo.png',
        status: 'Новая',
        response: false,
        youResponded: false,
        name: 'Медсестра',
        logo: 'img/Logo.png',
        salary: '10 000 — 15 000 ₴',
        comment: 'Ставка + процент от продаж',
        сompanyName: 'FISHKI.UA',
        city: 'Киев',
        benefits: [
            
        ],
        publicationTime: 'publicationTime',
        response: 'response',
        addToFavorites: 'addToFavorites',
        disLike: false,
    },
    {
        id: '10',
        promoImg: 'img/Prof-Photo.png',
        status: 'Новая',
        response: false,
        youResponded: false,
        name: 'Бухгалтер',
        logo: 'img/Logo.png',
        salary: '10 000 — 15 000 ₴',
        comment: 'Ставка + процент от продаж',
        сompanyName: 'FISHKI.UA',
        city: 'Киев',
        benefits: [
            'Обеды в офис','Гибкий график','Компенсация спортзала'
        ],
        publicationTime: 'publicationTime',
        response: 'response',
        addToFavorites: 'addToFavorites',
        disLike: false,
    },
]